version: '3.8'

services:
  incident_recommender:
    build: .
    container_name: ml_flask_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  jupyter_notebook:
    image: jupyter/base-notebook
    working_dir: /notebooks
    ports:
      - 8888:8888
    container_name: jupyter_notebook_container
    command: "jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root"